name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node:
          - 14
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    name: "${{matrix.platform}} w/ Node.js ${{matrix.node}}.x"
    runs-on: ${{matrix.platform}}
    needs: chore

    steps:
      - uses: actions/checkout@v3

      - name: "Use Node.js ${{matrix.node}}.x"
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node}}.x

      - run: corepack yarn install
      - run: corepack yarn build # We need the stubs to run the tests

      - name: "Check for type errors"
        run: corepack yarn typecheck

      - name: "Check for linting errors"
        run: corepack yarn lint

      - name: "Check for failing tests"
        run: corepack yarn test
